### ISSUE TITLE
How to customize version of a checker?

### ISSUE THREAD

**Issue by atugushev** [LambdaLint/lambdalint.github.io#5]
For example if a project needs `flake8==3.5.0`?

**Comment by codingjoe** [comment]
Hi @atugushev you currently can't, since the linter is preinstalled in the AWS lambda function. I know that AWS can retain multiple versions of a function, but I haven't used that feature yet. Beyond that, it would be possible to create a function for each version. I don't know if any of these scenarios is feasible, since it would involve a lot of manual labor to set up the SNS subscriptions.

I would love to make this possible at some point, but I can say for sure, this won't happen any time soon :/
